name: "DEV DEPLOY"

on:
 push:
  branches:
     -developer

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
   uses: ./.github/workflows/terraform.yml
   with:
    environment: dev
    aws-assume-role-arn: "arn:aws:iam::058264514003:role/github-actions-bellasuto-pipeline"
    aws-region: "sa-east-1"
    aws-statefile-s3-bucket: "bellasuto-sa-east-1-terraform"
    aws-lock-dynambd-table: "bellasuto-sa-east-1-terraform-lock
"
